### ISSUE TITLE
Boolean Support

### ISSUE THREAD

**Issue by jtwebman** [bitbutcher/accurized#1]
How would you validate a boolean value that could be not set at all but if is needs to be true or false?

**Comment by bitbutcher** [comment]
An example while validating a json submission.
```coffee
accurized.data (json, req, res, next) ->
  #...
  json.field('flag', "The flag, if specified, must be 'true' or 'false'.").trim().optional().boolean().as 'boolean'
  #...
```

**Comment by jtwebman** [comment]
Thanks!

**Comment by jtwebman** [comment]
Basically I need this

```coffeescript
if typeof req.body.value != 'undefined' && req.body.value != null && typeof req.body.value != 'boolean'
```

**Comment by bitbutcher** [comment]
Happy to help.  It sounds like this answers your question.  I'm going to close the issue.

**Comment by jtwebman** [comment]
So there is no way to do it in the library?

**Comment by bitbutcher** [comment]
Accurized's built in validators are based on node-validator which is really only meant for validating, cleansing and coercing input strings.  In practice this generally works fine for JSON as well since JSON encodable data reliably coerces into strings and you specify the data type you ultimately want via the `as 'boolean'` call.  If you don't like the built in validator you can always implement your own via:
``` coffee
accurized.data (json, req, res, next) ->
  #...
  json.field('flag', 'The flag, if specified, must be a boolean value').optional().as 'boolean', (flag, pass, fail) ->
    return fail() unless typeof flag is 'boolean'
    pass flag
  #...
```

One thing to note is that.  If the key is set to anything other than undefined including null in the JSON the field will be validated.  With accurized optional means it can be omitted not that it can be explicitly set to null.

**Comment by jtwebman** [comment]
The issue with you code is the the `json.field('flag', 'The flag, if specified, must be a boolean value').optional().as 'boolean'` converts value to boolean even in the custom validator. So string 'true' is true number 1 is true and 0 is false even though in the API this is not what they sent. JSON allows for null, boolean, number, string, array, and object types. The body parser took the string from the req and made it a JSON object in body so the library should have a fail if not type and set. Something like this...

```coffeescript
json.field('flag', 'The flag, if specified, must be a boolean value.').optional().as (flag, pass, fail) ->
    return fail() unless typeof flag is 'boolean' or flag == null
    pass flag
```

The optional would run if the property was passed and by not passing type it just runs the raw function with no casting.
